Vagrant.configure("2") do |config|
config.vm.box = "ubuntu/focal64"
config.ssh.insert_key = false

config.vm.define "server" do |server|
server.vm.hostname = "server"
server.vm.network "private_network", ip: "192.168.56.10"

server.vm.provider "virtualbox" do |vb|
vb.name = "vagrant-server"
vb.memory = 1024
vb.cpus = 1
end

server.vm.synced_folder ".", "/vagrant", type: "virtualbox"
server.vm.provision "shell", path: "provision_server.sh", privileged: true
end



config.vm.define "client" do |client|
client.vm.hostname = "client"
client.vm.network "private_network", ip: "192.168.56.11"

client.vm.provider "virtualbox" do |vb|
vb.name = "vagrant-client"
vb.memory = 512
vb.cpus = 1
end

client.vm.synced_folder ".", "/vagrant", type: "virtualbox"
client.vm.provision "shell", path: "provision_client.sh", privileged: true
end
end