server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D
server.tomcat.accesslog.directory=/dev/stdout
server.tomcat.accesslog.suffix=-access.log

logging.level.org.springframework.web=DEBUG
logging.level.org.apache.catalina=INFO
