- hosts: wordpress
  become: true
  vars:
    wp_site_dir: /var/www/wordpress
  roles:
    - role: mysql
    - role: apache

  tasks:
    - name: Ensure wordpress directory exists
      file:
        path: "{{ wp_site_dir }}"
        state: directory
        owner: "{{ (ansible_facts['os_family'] == 'Debian') | ternary('www-data','apache') }}"
        group: "{{ (ansible_facts['os_family'] == 'Debian') | ternary('www-data','apache') }}"
        mode: '0755'

    - name: Download latest WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress-latest.tar.gz
        mode: '0644'

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress-latest.tar.gz
        dest: /var/www/
        remote_src: yes
        creates: /var/www/wordpress/index.php

    - name: Set ownership of WordPress files
      file:
        path: /var/www/wordpress
        state: directory
        recurse: yes
        owner: "{{ (ansible_facts['os_family'] == 'Debian') | ternary('www-data','apache') }}"
        group: "{{ (ansible_facts['os_family'] == 'Debian') | ternary('www-data','apache') }}"

    - name: Create wp-config.php from template
      template:
        src: wp-config.php.j2
        dest: /var/www/wordpress/wp-config.php
        owner: "{{ (ansible_facts['os_family'] == 'Debian') | ternary('www-data','apache') }}"
        group: "{{ (ansible_facts['os_family'] == 'Debian') | ternary('www-data','apache') }}"
        mode: '0644'
