Vagrant.configure("2") do |config|
config.vm.box = "ubuntu/focal64"
config.ssh.insert_key = false

config.vm.define "prod" do |prod|
prod.vm.hostname = "prod"
prod.vm.network "public_network", ip: "192.168.1.210"

prod.vm.provider "virtualbox" do |vb|
vb.name = "vagrant-prod"
vb.memory = 1024
vb.cpus = 1
end

prod.vm.synced_folder ".", "/vagrant", type: "virtualbox"
prod.vm.provision "shell", path: "provision_prod.sh", privileged: true
end



config.vm.define "dev" do |dev|
dev.vm.hostname = "dev"
dev.vm.network "public_network", ip: "192.168.1.211"

dev.vm.provider "virtualbox" do |vb|
vb.name = "vagrant-dev"
vb.memory = 512
vb.cpus = 1
end

dev.vm.synced_folder ".", "/vagrant", type: "virtualbox"
dev.vm.provision "shell", path: "provision_dev.sh", privileged: true
end
end