Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  
  config.vm.synced_folder ".", "/vagrant"

  # Server
  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.10"
    server.vm.provision "shell", path: "provision_server.sh"
  end

  # Client
  config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.56.11"
    client.vm.provision "shell", path: "provision_client.sh"
  end
end