apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.mysql.service.port }}
    name: mysql
  selector:
    app: mysql
  clusterIP: None
