apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.wordpress.storage.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.wordpress.storage.size | quote }}
