---
- name: Install packages and ensure nginx running; show environment
  hosts: servers
  become: yes
  vars:
    packages:
      - wget
      - htop
      - nginx

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name: "{{ packages }}"
        state: present

    - name: Ensure nginx is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Show environment of the host
      debug:
        msg: "This host is in {{ hostvars[inventory_hostname].env | default('unknown') }} environment"
