{
 "title": "Reddit App",
 "tags": [ "reddit" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Общее число запросов к ui",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(probe_success{job=~\"blackbox-ui-.*\"}[5m]))",
     "legendFormat": "{{instance}} - {{path}}"
    }
   ]
  },
  {
   "title": "Трафик запросов (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(probe_duration_seconds{job=~\"blackbox-ui-.*\"}[1m]))",
     "legendFormat": "{{instance}} - {{path}}"
    }
   ]
  },
  {
   "title": "90-ый перцентиль время ответа",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "quantile_over_time(0.9, probe_duration_seconds{job=~\"blackbox-ui-.*\"}[5m])",
     "legendFormat": "{{instance}} - {{path}}"
    }
   ]
  }
 ]
}